Testing addUser shopper1 ... ok!
Testing addUser shopper1 duplicate ... ok!
Adding all users  ... ok!
Testing login for all users ... ok!
Testing addCategory for a shopper ... ok!
Testing addCategory TSHIRT for admins ... ok!
Testing addCategory BOOK for admins ... ok!
Testing addRoute for admin ... ok!
Testing addDistributionCenter  ... ok!
Testing addCustomer for Shopper1 ... ok!
-Testing addCustomer for duplicates: adding Shopper1 again ... failed!
Testing addCustomer  ... ok!
Testing addProduct for a shopper ... ok!
Test adding all products ... ok!
Testing prodInquiry prodID=9999 ... ok!
Testing prodInquiry non existent center X ... ok!
Testing updateQuantity for prodID=9999 ... ok!
Testing updateQuantity prodID=1 center X ... ok!
Testing update quantity, trying to add 100 units of prodID= 1 to warehouse A
-Testing updateQuantity ... failed, exception:
java.lang.NullPointerException
	at api.DistributionCentre.addQty(DistributionCentre.java:59)
	at api.Administrator.updateQty(Administrator.java:135)
	at api.Project.updateQuantity(Project.java:278)
	at api.ProjectTest.test3UpdateQuantity(ProjectTest.java:543)
	at api.ProjectTest.testAll(ProjectTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing prodInquiry prodID=1 warehouse A expected 100 ... got -1, failed!
-Testing placeOrder, shopper=B, Prod=1, qty = 100 ... orderID test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test1PlaceOrder(ProjectTest.java:609)
	at api.ProjectTest.testAll(ProjectTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=B, Prod=1, qty = 100 ... inventory balance test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test1PlaceOrder(ProjectTest.java:609)
	at api.ProjectTest.testAll(ProjectTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=B, Prod=1, qty = 100 ... invoice test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test1PlaceOrder(ProjectTest.java:609)
	at api.ProjectTest.testAll(ProjectTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=B, Prod=1, qty = 100 ... route test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test1PlaceOrder(ProjectTest.java:609)
	at api.ProjectTest.testAll(ProjectTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Testing placeOrder, shopper=B, Prod=4, qty = 4000 ...  orderID ok!
-Testing placeOrder, shopper=B, Prod=4, qty = 4000 ...  inventory balance -3, expected 6000
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... orderID test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test3PlaceOrder(ProjectTest.java:712)
	at api.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... inventory balance test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test3PlaceOrder(ProjectTest.java:712)
	at api.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... invoice test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test3PlaceOrder(ProjectTest.java:712)
	at api.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... route test failed, exception:
java.lang.NullPointerException
	at api.Customer.getDeliRoute(Customer.java:91)
	at api.Project.getDeliveryRoute(Project.java:357)
	at api.ProjectTest.test3PlaceOrder(ProjectTest.java:712)
	at api.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Testing placeOrder, user not logged in ...  ok!
Testing placeOrder, user admin ...   ok!
